# Generated by Django 5.0.1 on 2024-02-05 06:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='defalut/default.png', upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
