# Generated by Django 5.0.1 on 2024-02-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
