# Generated by Django 5.0.1 on 2024-02-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_custom_url_urlshortener_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortener',
            old_name='short_url',
            new_name='custom_url',
        ),
    ]
