# Generated by Django 5.0.1 on 2024-02-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_short_url_urlshortener_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='original_url',
            field=models.URLField(),
        ),
    ]
